# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('origin_url', models.URLField()),
                ('author', models.CharField(blank=True, max_length=32)),
                ('addtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('tool', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('datetime', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.Article')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(max_length=8)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('tag', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64)),
                ('device_platform', models.CharField(blank=True, max_length=16)),
                ('device_model', models.CharField(blank=True, max_length=16)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('last_visit_time', models.DateTimeField(auto_now=True)),
                ('associate_article_ids', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitNum',
            fields=[
                ('visitnum_id', models.AutoField(primary_key=True, serialize=False)),
                ('pv', models.IntegerField(default=0)),
                ('uv', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.Article')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.Source'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdut.Type'),
        ),
    ]
