# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.TextField(),
        ),
    ]
